apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
  namespace: ml-api
  labels:
    app: ml-api
spec:
  type: ClusterIP
  selector:
    app: ml-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None