apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ml-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
{{- end }}

