apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ml-api.labels" . | nindent 4 }}
    app: {{ include "ml-api.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ml-api.name" . }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  sessionAffinity: None
